language: c++
env:
  global:
    - TWINE_USERNAME=ccubed

matrix:
  include:
    - sudo: required
      services:
        - docker
    - os: osx

script:
  - pip install git+https://github.com/ccubed/Earl.git
  - cibuildwheel --output-dir wheelhouse
  - |
    if [[ $TRAVIS_TAG ]]; then
      python -m pip install twine
      python -m twine upload wheelhouse/*.whl
    fi