language: python
python:
  - "3.5"

install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install g++-4.8 gcc-4.8; else brew install gcc48; fi
  
env:
  global:
    - TWINE_USERNAME=ccubed

matrix:
  include:
    - sudo: required
      services:
        - docker
    - os: osx

script:
  - CC=gcc-4.8 CXX=g++-4.8 pip install git+https://github.com/ccubed/Earl.git
  - cibuildwheel --output-dir wheelhouse
  - |
    if [[ $TRAVIS_TAG ]]; then
      python -m pip install twine
      python -m twine upload wheelhouse/*.whl
    fi